blank_issues_enabled: false
contact_links:
  # - name: üöÄ Feature Request
  #   url: https://github.com/alienator88/Pearcleaner/discussions/new?category=general
  #   about: Share ideas for new features
  - name: ‚ùì Ask a Question
    url: https://github.com/alienator88/Pearcleaner/discussions/new?category=general
    about: Ask the community for help
  - name: I WILL BE TAKING A BREAK DURING DECEMBER
    url: https://github.com/alienator88/Pearcleaner
    about: BUGS/FRs will not be looked at much, if at all
