blank_issues_enabled: false
contact_links:
  - name: PEARCLEANER IS NOW IN MAINTENANCE MODE
    url: https://github.com/alienator88/Pearcleaner/blob/main/.github/ISSUE_TEMPLATE/project.md
    about: FRs will be ignored/closed. Click here for more details.
  - name: ‚ùì Ask a Question
    url: https://github.com/alienator88/Pearcleaner/discussions/new?category=general
    about: Ask the community for help
  
